STATE_DATA_KEY = "state_data"
PERTURBATION_DATA_KEY = "condition"
PERTURBATION_TARGET_REPR_KEY = "perturbation_target_repr"
SOURCE_STATE_KEY = "source"
TARGET_STATE_KEY = "target"
CONDITION_REP_KEY = "repr"
CONDITION_COV_KEY = "cov"

LOSS_KEY = "loss"
VF_LOSS_KEY = "vf_loss"
SCORE_LOSS_KEY = "score_loss"
SOURCE_LOSS_KEY = "src_posterior_loss"
TARGET_LOSS_KEY = "tgt_posterior_loss"
PERTURBATION_LOSS_KEY = "pert_posterior_loss"
LATENT_PERTURBATION_REG_LOSS_KEY = "latent_pert_regulation"
LATENT_PERTURBATION_INF_LOSS_KEY = "latent_pert_inference_loss"

MEAN_KEY = "mean"
COVARIANCE_KEY = "covariance"

VF_KEY = "vf"
SCORE_KEY = "score"
LATENT_REPR_KEY = "latent_repr"
LATENT_STATE_KEY = "xt_latent"
LATENT_TIME_KEY = "t_latent"
LATENT_PERTURBATION_KEY = "cond_latent"
SOURCE_PARAMS_KEY = "src_posterior_params"
TARGET_PARAMS_KEY = "tgt_posterior_params"
PERTURBATION_PARAMS_KEYS = "pert_posterior_params"

TARGET_CATEGORIES_KEY = "target_categories"
